### ISSUE TITLE
Fluent parser: parse_resource() bails for syntax errors

### ISSUE THREAD

**Issue by flodolo** [mozilla/moz-l10n#10]
Take for example this content

```
some junk text, should be ignored

# Parameterized term
onboarding-fxa-text = Зарегистрируйте { -fxaccount-brand-name(case: "nominative") } test.
```

compare-locales would report the `junk`, but keep parsing. `parse_resource()` seems to stop completely and raise an exception

```
ValueError: Expected token: "="
```

Would it be possible to have a similar behavior?

**Comment by eemeli** [comment]
Not really. This is an intentional design choice, to require and enforce validity in source files, rather than supporting fallback with something like junk.

The thinking here is that when encountering a broken file, the right thing to do is to force the file to be fixed before it goes any further in our processing.

**Comment by flodolo** [comment]
What happens in a Pontoon scenario when the file is broken, but this is not immediately visible? Do we risk losing translations, for example, because the file is suddenly parsed as empty?

**Comment by flodolo** [comment]
BTW, I have a similar error with a file (not ftl) with broken encoding.

What is the behavior of other popular parsers? What is the risk we're taking here by enforcing sanity?

**Comment by eemeli** [comment]
> What happens in a Pontoon scenario when the file is broken, but this is not immediately visible? Do we risk losing translations, for example, because the file is suddenly parsed as empty?

A broken file results in a parse error, which is distinct from an empty resource. If this happens with a source file, we won't update any of the file's messages. If it happens with a target file, we probably shouldn't sync that file for that locale at all. In both cases, we'll need to ensure that the error is clearly communicated.

> What is the behavior of other popular parsers? What is the risk we're taking here by enforcing sanity?

In general, compare-locales is an outlier in its recovery from broken files. Failing on error is the usual practice.

Done right, the changes we're making should not introduce any new risks; rather, they'll let us catch errors closer to their source, where they're easier to fix.

**Comment by flodolo** [comment]
I'm guessing the same goes for a file with encoding problems? (I think this is my [test file](https://github.com/flodolo/tmx_maker/blob/main/tests/testfiles/tmx/oc/mail/mailTurboMenu.properties), but on a different device at the moment)

Unless @mathjazz has a strong opinion on this, I guess we can close. We should probably document that somewhere.

**Comment by eemeli** [comment]
If you're working with files that have an encoding other than UTF-8, then you're probably best off decoding it separately and feeding in the string value. This should be better documented; it's an optimization that's valid since all the files we actually deal with are UTF-8, but should be revisited if the need arises.

**Comment by mathjazz** [comment]
> Unless @mathjazz has a strong opinion on this, I guess we can close.

Not really, I'm aware of how this behaviour.
